services:
  - type: web
    name: employee-management-api
    runtime: docker
    plan: free
    dockerfilePath: ./dockerfile
    envVars:
      - key: DB_URL
        fromDatabase:
          name: employee-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: employee-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: employee-db
          property: password
      - key: APP_JWT_SECRET
        generateValue: true
      - key: APP_JWT_EXPIRATION
        value: 86400000
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: ADMIN_PASSWORD
        sync: false

databases:
  - name: employee-db
    plan: free
    databaseName: employee_management
    user: employee_user
