services:
  - type: web
    name: employee-management-api
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/employeeManagement-0.0.1-SNAPSHOT.jar
    envVars:
      - key: DB_URL
        value: jdbc:postgresql://dpg-ctqhvgl6l47c73a0vu3g-a.oregon-postgres.render.com:5432/railway_db_xxxx
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        sync: false
      - key: APP_JWT_SECRET
        generateValue: true
      - key: APP_JWT_EXPIRATION
        value: 86400000
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: ADMIN_PASSWORD
        sync: false
